version: '2.4'

services:
  nodejs-scaffold:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
    - .:/app:delegated
  proxy:
    volumes:
    - ./nginx_local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 80:80
    image: nginx:1.15-alpine