version: '2.4'

services:
  nodejs-scaffold:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
    - ./.env:/app/.env:ro
  proxy:
    volumes:
    - ./nginx/logs:/var/log/nginx
    - ./nginx_local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 80:80
    image: nginx:stable